# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('exploBATCH_rcpparma_hello_world', PACKAGE = 'exploBATCH')
}

rcpparma_outerproduct <- function(x) {
    .Call('exploBATCH_rcpparma_outerproduct', PACKAGE = 'exploBATCH', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('exploBATCH_rcpparma_innerproduct', PACKAGE = 'exploBATCH', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('exploBATCH_rcpparma_bothproducts', PACKAGE = 'exploBATCH', x)
}

fM <- function(A, B) {
    .Call('exploBATCH_fM', PACKAGE = 'exploBATCH', A, B)
}

